sudo: required
services:
    - docker

before_install:
    - docker build -t lombaardj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lombaardj/docker-react npm run test -- --coverage